### ISSUE TITLE
Multiple Instances Monitoring

### ISSUE THREAD

**Issue by iadegesso** [ziyagenc/phi#1] opened 2023-10-17 19:05 UTC
Hi,
do you think its hard to add a new features to allow simultaneous monitoring of multiple pi-hole instances in the same network?

Thanks,

Iade

**Comment by ziyagenc** [comment] 2023-10-17 21:05
Hi Iade, 

It would not be difficult to add the capability of monitoring multiple Pi-hole instances, as Phi is designed in layers. However, reporting statistics to user while maintaining usability seems not an easy task in multi-instance case, and I want to keep Phi simple and usable (not only its main UI, but also its settings interface).

That said, I want to explore this further and decide after gathering more data. To begin with, if we are considering two instances in total (please let me know otherwise), statistics can be reported in a single menu, as done in the attached screenshot:

![Reporting two instances](https://github.com/ziyagenc/phi/assets/26028339/2ed1e771-b99d-46f8-bb31-4453e63f4533)

We will still have issues with toggle button (states of Pi-holes can be changed outside the extension) and version information (they can have different versions of Pi-hole software). 

Another option could be sub-menus, where things start being complex (click to access/close sub-menus, more area covered at screen). Aggregated statistics might also be an option, but I guess this is the least interesting one at the moment.

Thanks for opening this issue. Any feedback/comment is appreciated.

**Comment by iadegesso** [comment] 2023-10-17 21:27
Hi,
and thank you for the quick reply. I was wondering about a simple home setup with two PiHoles (primary and secondary local DNS). So your idea shown in the screenshot will be good for me.

Monitoring more than two PiHoles can be done using NodeRED, and I think this setup can be found in enterprise environments...


Iade

**Comment by ziyagenc** [comment] 2023-10-22 18:56
Thanks for the feedback. The commit 318c091 makes Phi capable of monitoring two Pi-hole instances on GNOME 44. The new version should be available at GNOME Extensions website soon.

If multi-instance mode is enabled, Phi displays statistics as shown in the attached screenshot.
![Screenshot from 2023-10-22 20-21-55](https://github.com/ziyagenc/phi/assets/26028339/1e091f8a-3ab8-443e-aefb-4c6cc2f0ea95)

Blocking status of an instance can be toggled by clicking the corresponding button. Instance names can be modified in the settings.

**Comment by iadegesso** [comment] 2023-10-27 21:29
It works in GNOME 45 too!

Iade

**Comment by ziyagenc** [comment] 2023-10-29 03:14
Yes, the main branch contains the version of Phi that is compatible with GNOME 45. 

In this release, the menu in multi-mode looks nice but there might be still room for improvement in the settings interface. We will explore it in next release.

Thanks again for opening this issue that helped making Phi more capable. Since the issue is now solved, I am going to close it.

**Closed by ziyagenc** 2023-10-29 03:14 UTC
Labels: enhancement
